import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import NotesPage from "~/components/Notes";
import GoogleSignInButton from "~/components/LoginButton";
import { useState } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Notes</title>
        <meta
          name="description"
          content="Notes app Generated by create-t3-app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/notes.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-shadow-lg fixed left-1/2 top-52 -translate-x-1/2 transform text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 bg-clip-text text-[hsl(280,100%,70%)] text-transparent">
              Notes
            </span>{" "}
            App
          </h1>
          <div className="md:gap-8">
            <NotesPage />
          </div>
          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: session } = useSession();
  const [isLogoutVisible, setIsLogoutVisible] = useState(false);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {session ? (
        <div
          className="fixed right-16 top-10 flex cursor-pointer items-center text-white"
          onClick={() => setIsLogoutVisible(!isLogoutVisible)}
        >
          <img
            src={session.user.image ?? "/default-profile.png"}
            className="mr-2 h-8 w-8 rounded-full"
          />
          <span text-white>{session.user.name}</span>
          {isLogoutVisible && (
            <button
              onClick={() => signOut()}
              className="absolute right-0 top-full mt-2 translate-y-0 transform rounded bg-red-400 px-4 py-2 font-bold text-white transition-transform"
            >
              Logout
            </button>
          )}
        </div>
      ) : (
        <GoogleSignInButton onClick={() => signIn("google")} />
      )}
    </div>
  );
}
